Milestone4 category filter
shloch/REACT_REDUX_BOOKSTORE pull request #4
Opened 2019-11-01 14:08 UTC by truetechcode

created filter reducer and action
stored filter in redux store

2019-11-04 12:49 UTC, SunnyAsar requested changes
# Hey @truetechcode  and @shloch 👋 
### well done guy, project is looking good.
I made some comments below, concerning the option-select like in the previous milestone. also a bout your approach to filter. Please send me slack message if there is any confusion.


**Please request another review with update**

2019-11-04 12:49 UTC, SunnyAsar commented on src/components/CategoryFilter.js
> +    <option value='default'>Filter Books</option>
Hey, this is not needed, i should be seeing `All` its all the books that are displayed at start after all.

2019-11-04 12:49 UTC, SunnyAsar commented on src/components/CategoryFilter.js
> +    <select name="category" onChange={(e) => props.onChange(e)}>
Naming functions the same as event handlers can get tricky maybe `handleChange`[OPTIONAL]

2019-11-04 12:49 UTC, SunnyAsar commented on src/containers/BooksList.js
> +  let filteredBooks = props.books.filter((book) => book.category === props.filter || props.filter === '')
we could do this at the state level and fetch only what we need.

2019-11-04 12:49 UTC, SunnyAsar commented on src/reducers/filter.js
> +      return 'Action'
Hi guys we can cut this down significantly like this:

action:
```
export const changeFilter = category => {
  return {
    type: `CHANGE_FILTER`,
    category
  }
}
```

reducer:
this way we can return exactly what is picked in category to be saved in store and use it to filter books.
```
switch (action.type) {
    case `CHANGE_FILTER`:
      return action.filter
    default:
      return state
  }
```

2019-11-05 08:53 UTC, BalintMendli approved these changes
Hi @truetechcode @shloch ,

Great job. It is a
### 👍 

You can merge the project.

2019-11-05 09:06 UTC, merged